Ecommerce.Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Service.Interface;
using EcommerceCommon.Infrastructure.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.Admin.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardService _dashboardService;

        public DashboardController(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var models = new DashboardViewModel
            {
                TotalOrder = await _dashboardService.GetTotalOrder(),
                NewUserRegisters = await _dashboardService.GetUserRegisters(),
                NewProduct = await _dashboardService.GetNewProduct(),
                MostViewProducts = await _dashboardService.GetProductView(),
                NewOrders = await _dashboardService.GetNewOrder()
            };
            return View(models);
        }

        /// <summary>
        /// New order
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> ListNewOrder()
        {
            var newOrder = await _dashboardService.GetNewOrder();
            return View(newOrder);
        }

        /// <summary>
        /// New product
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> NewProduct()
        {
            var newProduct = await _dashboardService.GetNewProduct();
            return View(newProduct);
        }

        /// <summary>
        /// New user
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> NewUser()
        {
            var users = await _dashboardService.GetUserRegisters();
            return View(users);
        }
    }
}

Ecommerce.Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Repository.Interfaces;
using Ecommerce.Service.Interface;
using EcommerceCommon.Infrastructure.Dto.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Ecommerce.Admin.Controllers
{
    public class ProductController : Controller
    {
        //private readonly IProductRepository _productRepository;
        //private readonly ICategoryRepository _categoryRepository;
        //private readonly ISupplierRepository _supplierRepository;
        //private readonly IManufactureRepository _manufactureRepository;

        //public ProductController(IProductRepository productRepository,
        //    ICategoryRepository categoryRepository,
        //    ISupplierRepository supplierRepository,
        //    IManufactureRepository manufactureRepository)
        //{
        //    _productRepository = productRepository;
        //    _categoryRepository = categoryRepository;
        //    _supplierRepository = supplierRepository;
        //    _manufactureRepository = manufactureRepository;
        //}

        private readonly IProductSevice _productSevice;
        private readonly ICategoryService _categoryService;
        private readonly ISupplierService _supplierService;
        private readonly IManufactureService _manufactureService;

        public ProductController(IProductSevice productSevice, 
            ICategoryService categoryService,
            ISupplierService supplierService,
            IManufactureService manufactureService)
        {
            _productSevice = productSevice;
            _categoryService = categoryService;
            _supplierService = supplierService;
            _manufactureService = manufactureService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid? categoryId)
        {
            ViewBag.Success = TempData["result"];

            var categories = await _categoryService.GetAllCategories();

            ViewBag.Categories = categories.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId == x.Id
            });

            var products = await _productSevice.GetAllProducts(categoryId);
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var product = await _productSevice.GetProductById(id);
            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var suppliers = await _supplierService.GetAll();

            ViewBag.Suppliers = suppliers.Select(x => new SelectListItem() { 
                Text = x.Name,
                Value = x.Id.ToString()
            });

            var manufactures = await _manufactureService.GetAll();

            ViewBag.Manufactures = manufactures.Select(x => new SelectListItem() { 
                Text = x.Name,
                Value = x.Id.ToString()
            });

            var categories = await _categoryService.GetAllCategories();

            ViewBag.Categories = categories.Select(x => new SelectListItem() { 
                Text = x.Name,
                Value = x.Id.ToString()
            });

            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]//cho phep nhan kieu du lieu truyen len la form-data
        public async Task<IActionResult> Create(ProductCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = await _productSevice.Create(dto);

            if (result)
            {
                TempData["result"] = "Thêm sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm sản phẩm thất bại");

            return View(dto);
        }
    }
}

Ecommerce.Admin/Views/Product/Create.cshtml
@model EcommerceCommon.Infrastructure.Dto.Product.ProductCreateDto

@{
    ViewData["Title"] = "Thêm mới sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .padd-left {
        padding-left: 0px !important;
    }
</style>

@section Scripts{
    <script src="~/js/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thêm mới sản phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <a asp-action="Index" class="btn btn-success">Về danh sách</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <form asp-controller="Product" asp-action="Create" method="post" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Code" class="control-label"></label>
                                <input asp-for="Code" class="form-control" />
                                <span asp-validation-for="Code" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Sku" class="control-label"></label>
                                <input asp-for="Sku" class="form-control" />
                                <span asp-validation-for="Sku" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublicationDate" class="control-label"></label>
                                <input asp-for="PublicationDate" class="form-control" />
                                <span asp-validation-for="PublicationDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ExpirationDate" class="control-label"></label>
                                <input asp-for="ExpirationDate" class="form-control" />
                                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PercentDiscount" class="control-label"></label>
                                <input asp-for="PercentDiscount" class="form-control" />
                                <span asp-validation-for="PercentDiscount" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Quantity" class="control-label"></label>
                                <input asp-for="Quantity" class="form-control" />
                                <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-5 padd-left">
                                <label asp-for="CategoryId" class="control-label"></label>
                                <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.Categories">
                                    <option>--Chọn danh mục--</option>
                                </select>
                                <span asp-validation-for="SupplierId" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-5 padd-left">
                                <label asp-for="SupplierId" class="control-label"></label>
                                <select asp-for="SupplierId" class="form-control" asp-items="@ViewBag.Suppliers">
                                    <option>--Chọn nhà cung cấp--</option>
                                </select>
                                <span asp-validation-for="SupplierId" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-5 padd-left">
                                <label asp-for="ManufactureId" class="control-label"></label>
                                <select asp-for="ManufactureId" class="form-control" asp-items="@ViewBag.Manufactures">
                                    <option>--Chọn nhà sản xuất--</option>
                                </select>
                                <span asp-validation-for="ManufactureId" class="text-danger"></span>
                            </div>
                            @*<div class="form-group">
                                    <label asp-for="ProductStatus" class="control-label"></label>
                                    <input asp-for="ProductStatus" class="form-control" />
                                    <span asp-validation-for="ProductStatus" class="text-danger"></span>
                                </div>*@
                            <div class="form-group">
                                <label asp-for="Keyword" class="control-label"></label>
                                <input asp-for="Keyword" class="form-control" />
                                <span asp-validation-for="Keyword" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea id="editor" rows="35" asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ShortDescription" class="control-label"></label>
                                <input asp-for="ShortDescription" class="form-control" />
                                <span asp-validation-for="ShortDescription" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Weight" class="control-label"></label>
                                <input asp-for="Weight" class="form-control" />
                                <span asp-validation-for="Weight" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Height" class="control-label"></label>
                                <input asp-for="Height" class="form-control" />
                                <span asp-validation-for="Height" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Width" class="control-label"></label>
                                <input asp-for="Width" class="form-control" />
                                <span asp-validation-for="Width" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ThumnailImage" class="control-label"></label>
                                <input type="file" asp-for="ThumnailImage" class="form-control" />
                                <span asp-validation-for="ThumnailImage" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Thêm mới" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- /.card-body -->
</section>

Ecommerce.Admin/Views/Product/Details.cshtml
@model EcommerceCommon.Infrastructure.ViewModel.Product.ProductViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thông tin người dùng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thông tin người dùng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <a asp-action="index" class="btn btn-success">Về danh sách</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Code)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Code)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Sku)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Sku)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PublicationDate)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PublicationDate)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PercentDiscount)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PercentDiscount)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Price)
                    </dt>
                    <dd class="col-sm-10">
                        @Model.Price.ToString("N0")
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Quantity)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Quantity)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ProductStatus)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ProductStatus)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Views)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Views)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Keyword)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Keyword)
                    </dd>
                    @*<dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ExpirationDate)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ExpirationDate)
                    </dd>*@
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ShortDescription)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ShortDescription)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Weight)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Weight)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Height)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Height)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Width)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Width)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.SupplierName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.SupplierName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ManufactureName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ManufactureName)
                    </dd>
                </dl>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</section>

Ecommerce.Admin/Views/Product/Index.cshtml
@using EcommerceCommon.Infrastructure.ViewModel.Product;
@model List<ProductViewModel>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section DataTable{
    <!-- DataTables -->
    <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
}

<style>
    .btn-action{
        line-height:1 !important;
    }
</style>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Danh sách sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Danh sách sản phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header row">
                <div class="col-md-9"><a asp-action="Create" class="btn btn-success">Thêm mới</a></div>
                <div class="col-md-3">
                    <form asp-action="Index" method="get">
                        <select onchange="this.form.submit()" name="categoryId" class="form-control" asp-items="@ViewBag.Categories">
                            <option>--Danh mục sản phẩm--</option>
                        </select>
                    </form>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                @if (@ViewBag.Success != null)
                {
                    <div id="msgSuccess" class="alert alert-success" role="alert">
                        @ViewBag.Success
                    </div>
                }
                <div class="table-responsive">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Mã sản phẩm</th>
                                <th>Tên SP</th>
                                <th>Số lượng</th>
                                <th>Giá</th>
                                <th>Trạng thái</th>
                                <th>Ngày mở bán</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Code</td>
                                    <td>@item.Name</td>
                                    <td>@item.Quantity</td>
                                    <td>
                                        @item.Price.ToString("N0")
                                    </td>
                                    @{
                                        if ((int)item.ProductStatus == 0)
                                        {
                                            <td>Còn hàng</td>
                                        }
                                        else if((int)item.ProductStatus == 1)
                                        {
                                            <td>Mới</td>
                                        }
                                        else if((int)item.ProductStatus == 2)
                                        {
                                            <td>Hết hàng</td>
                                        }
                                    }
                                    <td>@item.PublicationDate.ToString("MM/dd/yyyy")</td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-action" })
                                        @Html.ActionLink("Xem chi tiết", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-action" })
                                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-action" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                </div>
                <!-- /.card-body -->
            </div>
    </div>
</section>

@section Scripts{
    <script src="/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        setTimeout(function () {
            $("#msgSuccess").fadeOut();
        }, 3000);

        $(function () {
            $("#example1").DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "language": {
                    "info": "Hiển thị _START_ đến _END_ trong _TOTAL_ bản ghi",
                    "search": "Tìm kiếm:",
                    "paginate": {
                        "first": "Đầu",
                        "last": "Cuối",
                        "next": "Sau",
                        "previous": "Trước"
                    },
                    "lengthMenu": "Hiển thị _MENU_ bản ghi",
                    "infoEmpty": "Hiển thị 0 đến 0 trong 0 bản ghi",
                    "emptyTable": "Không có dữ liệu trong bảng",
                },
                "zeroRecords": "Không tìm thấy bản ghi nào",
            });
        });
    </script>
}